import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, CheckCircle2, ChevronRight, FileSearch, Flame, LayoutDashboard, Plus, Save, Sparkles, Target, Trash2, WandSparkles } from 'lucide-react';
import { api } from './api';
import type { Analysis, Application, Status } from './types';

const sampleResume=`Alex Morgan — Software Engineer\nFive years building reliable web products with TypeScript, React, Node.js, PostgreSQL, and AWS. Led a checkout redesign that improved conversion 18% and reduced page latency 40%. Designed REST APIs serving 2M requests per day. Mentored three junior engineers and partnered with product and design on quarterly planning. Built CI/CD pipelines with GitHub Actions and comprehensive unit and integration test suites.`;
const sampleJob=`We are hiring a Senior Product Software Engineer to build high-quality customer experiences. You will own projects end-to-end, work with product and design, and build scalable systems using TypeScript, React, Node.js, PostgreSQL, and AWS. You should have 4+ years of experience, excellent communication, API design expertise, testing discipline, and experience mentoring engineers. Experience with distributed systems and Kubernetes is preferred.`;

function App(){
  const [view,setView]=useState<'dashboard'|'analyze'|'tracker'>('dashboard');
  const [apps,setApps]=useState<Application[]>([]); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [mode,setMode]=useState('');
  useEffect(()=>{api.applications().then(setApps).catch(()=>setError('Could not load applications.'));},[]);
  const stats=useMemo(()=>({active:apps.filter(a=>!['Rejected','Offer'].includes(a.status)).length, interviews:apps.filter(a=>a.status==='Interview').length, avg:apps.length?Math.round(apps.reduce((n,a)=>n+a.fitScore,0)/apps.length):0}),[apps]);
  const analyze=async(data:{resume:string;jobDescription:string;company:string;role:string})=>{setLoading(true);setError('');setNotice('');try{const result=await api.analyze(data);setAnalysis(result.data);setMode(result.mode);}catch(e){setError(e instanceof Error?e.message:'Analysis failed');}finally{setLoading(false);}};
  const save=async(data:Omit<Application,'id'>)=>{setError('');try{const saved=await api.addApplication(data);setApps(current=>[saved,...current]);setNotice(`${saved.company} was added to your pipeline.`);}catch(e){setError(e instanceof Error?e.message:'Could not save application.');}};
  const updateStatus=async(id:string,status:Status)=>{setError('');try{const updated=await api.updateApplication(id,status);setApps(current=>current.map(item=>item.id===id?updated:item));setNotice('Application status updated.');}catch(e){setError(e instanceof Error?e.message:'Could not update status.');}};
  const remove=async(id:string)=>{setError('');try{await api.removeApplication(id);setApps(current=>current.filter(item=>item.id!==id));setNotice('Application removed.');}catch(e){setError(e instanceof Error?e.message:'Could not remove application.');}};
  return <div className="shell"><aside><div className="brand"><span>CF</span>CareerForge</div><nav><Nav icon={<LayoutDashboard/>} label="Overview" active={view==='dashboard'} onClick={()=>setView('dashboard')}/><Nav icon={<WandSparkles/>} label="AI Match Lab" active={view==='analyze'} onClick={()=>setView('analyze')}/><Nav icon={<BriefcaseBusiness/>} label="Application Tracker" active={view==='tracker'} onClick={()=>setView('tracker')}/></nav><div className="aside-card"><Sparkles/><strong>Career momentum</strong><p>3 applications this week. Keep the signal high.</p><div className="progress"><i style={{width:'68%'}}/></div></div><div className="profile"><div>AM</div><span><strong>Alex Morgan</strong><small>Software Engineer</small></span></div></aside>
  <main><header><div><small>JOB SEARCH OS</small><h1>{view==='dashboard'?'Make your next move count.':view==='analyze'?'AI Match Lab':'Application Tracker'}</h1></div><button className="primary" onClick={()=>setView('analyze')}><Plus/> Analyze a role</button></header>
  {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status"><CheckCircle2/>{notice}</div>}{view==='dashboard'&&<Dashboard apps={apps} stats={stats} go={()=>setView('analyze')}/>} {view==='analyze'&&<Analyzer loading={loading} result={analysis} mode={mode} onAnalyze={analyze} onSave={save}/>} {view==='tracker'&&<Tracker apps={apps} onStatus={updateStatus} onRemove={remove}/>}</main></div>
}
function Nav({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}){return <button className={active?'active':''} onClick={onClick}>{icon}{label}</button>}
function Dashboard({apps,stats,go}:{apps:Application[];stats:{active:number;interviews:number;avg:number};go:()=>void}){return <><section className="hero"><div><span className="eyebrow"><Flame/> YOUR FOCUS THIS WEEK</span><h2>Quality applications beat<br/>an empty pipeline.</h2><p>Run one high-fit role through the Match Lab, tailor your story, and send it today.</p><button className="ink" onClick={go}>Start a job analysis <ArrowRight/></button></div><div className="score-orbit"><div><small>PROFILE<br/>STRENGTH</small><b>84</b><span>/100</span></div></div></section><section className="stats"><Stat icon={<Target/>} value={stats.active} label="Active applications" note="Across your pipeline"/><Stat icon={<BarChart3/>} value={`${stats.avg}%`} label="Average role fit" note="Strong positioning"/><Stat icon={<BriefcaseBusiness/>} value={stats.interviews} label="Interviews" note="Keep preparing"/></section><div className="section-head"><div><small>PIPELINE</small><h2>Recent applications</h2></div><button className="text-btn">View all <ChevronRight/></button></div><ApplicationTable apps={apps.slice(0,4)}/></>}
function Stat({icon,value,label,note}:{icon:React.ReactNode;value:string|number;label:string;note:string}){return <article className="stat"><div className="stat-icon">{icon}</div><b>{value}</b><h3>{label}</h3><p><Check/> {note}</p></article>}
function Analyzer({loading,result,mode,onAnalyze,onSave}:{loading:boolean;result:Analysis|null;mode:string;onAnalyze:(x:{resume:string;jobDescription:string;company:string;role:string})=>void;onSave:(x:Omit<Application,'id'>)=>void}){const [resume,setResume]=useState(sampleResume),[job,setJob]=useState(sampleJob),[company,setCompany]=useState('Northstar'),[role,setRole]=useState('Senior Product Engineer'); return <div className="lab"><section className="form-card"><div className="section-head"><div><small>INPUTS</small><h2>Compare your evidence</h2></div><FileSearch/></div><div className="two"><label>Company<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)}/></label></div><label>Your resume<textarea value={resume} onChange={e=>setResume(e.target.value)} rows={10}/><small>{resume.length} characters</small></label><label>Job description<textarea value={job} onChange={e=>setJob(e.target.value)} rows={10}/><small>{job.length} characters</small></label><button className="primary wide" disabled={loading} onClick={()=>onAnalyze({resume,jobDescription:job,company,role})}><Sparkles/>{loading?'Analyzing evidence…':'Generate match strategy'}</button></section>{result?<Results data={result} mode={mode} onSave={()=>onSave({company:company.trim(),role:role.trim(),status:'Saved',fitScore:result.fitScore,date:new Date().toISOString().slice(0,10),location:'Remote'})}/>:<section className="empty"><div><WandSparkles/></div><h2>Your strategy appears here</h2><p>Get a grounded fit score, evidence gaps, resume actions, a cover letter draft, and interview questions.</p></section>}</div>}
function Results({data,mode,onSave}:{data:Analysis;mode:string;onSave:()=>void}){return <section className="results"><div className="result-hero"><div className="mini-score"><b>{data.fitScore}</b><span>/100</span></div><div><small>{mode==='ai'?'AI ANALYSIS':'DEMO ANALYSIS'}</small><h2>{data.verdict}</h2></div><button className="save-result" onClick={onSave}><Save/> Save to pipeline</button></div><Result title="Why you match" items={data.strengths}/><Result title="Gaps to address" items={data.gaps}/><div className="result-block"><small>MISSING KEYWORDS</small><div className="chips">{data.missingKeywords.map(x=><span key={x}>{x}</span>)}</div></div><Result title="Resume action plan" items={data.resumeRewrite}/><div className="result-block"><small>COVER LETTER DRAFT</small><p className="letter">{data.coverLetter}</p></div><div className="result-block"><small>INTERVIEW PREP</small>{data.interviewQuestions.map(q=><div className="question" key={q.question}><strong>{q.question}</strong><p>{q.strategy}</p></div>)}</div></section>}
function Result({title,items}:{title:string;items:string[]}){return <div className="result-block"><small>{title.toUpperCase()}</small><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div>}
function Tracker({apps,onStatus,onRemove}:{apps:Application[];onStatus:(id:string,status:Status)=>void;onRemove:(id:string)=>void}){return <><div className="section-head standalone"><div><small>ALL ROLES</small><h2>Your active pipeline</h2></div><span className="count">{apps.length} roles</span></div><ApplicationTable apps={apps} onStatus={onStatus} onRemove={onRemove}/></>}
function ApplicationTable({apps,onStatus,onRemove}:{apps:Application[];onStatus?:(id:string,status:Status)=>void;onRemove?:(id:string)=>void}){return <div className={`table ${onStatus?'editable':''}`}><div className="tr head"><span>Company & role</span><span>Status</span><span>Fit</span><span>{onStatus?'Actions':'Date added'}</span></div>{apps.map(a=><div className="tr" key={a.id}><span className="company"><i>{a.company[0]}</i><span><strong>{a.company}</strong><small>{a.role} · {a.location}</small></span></span><span>{onStatus?<select className="status-select" aria-label={`Status for ${a.company}`} value={a.status} onChange={e=>onStatus(a.id,e.target.value as Status)}>{(['Saved','Applied','Interview','Offer','Rejected'] as Status[]).map(status=><option key={status}>{status}</option>)}</select>:<StatusPill status={a.status}/>}</span><span className="fit"><i style={{width:`${a.fitScore}%`}}/><b>{a.fitScore}%</b></span><span>{onRemove?<button className="icon-button" aria-label={`Remove ${a.company}`} onClick={()=>{if(window.confirm(`Remove ${a.company} from your pipeline?`))onRemove(a.id);}}><Trash2/></button>:new Date(a.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div>)}</div>}
function StatusPill({status}:{status:Status}){return <em className={`status ${status.toLowerCase()}`}>{status}</em>}
export default App;
